// <auto-generated />
using System;
using ATag.EntityFrameworkCore.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ATag.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(TagsDbContext))]
    partial class TagsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "1.1.2");

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ATag.Core.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("CreatedByUserId");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedOn");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("ModifiedByUserId");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedOn");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Name");

                    b.Property<string>("OwnerId")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("OwnerId");

                    b.Property<int>("OwnerType")
                        .HasColumnType("int")
                        .HasColumnName("OwnerType");

                    b.HasKey("Id");

                    b.HasIndex("OwnerType", "OwnerId")
                        .HasDatabaseName("IX_Tag_OwnerType_OwnerId");

                    b.ToTable("Tag", "dbo");
                });

            modelBuilder.Entity("ATag.Core.TaggedEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("CreatedByUserId");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedOn");

                    b.Property<string>("EntityKey")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("EntityKey");

                    b.Property<string>("EntityType")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("EntityType");

                    b.Property<int>("TagId")
                        .HasColumnType("int")
                        .HasColumnName("TagId");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("EntityType", "EntityKey", "TagId")
                        .HasDatabaseName("IX_TaggedEntity_EntityType_EntityKey_TagId");

                    b.ToTable("TaggedEntity", "dbo");
                });

            modelBuilder.Entity("ATag.Core.TagNote", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("CreatedByUserId");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedOn");

                    b.Property<int?>("ModifiedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("ModifiedByUserId");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedOn");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Note");

                    b.HasKey("Id");

                    b.ToTable("TagNote", "dbo");
                });

            modelBuilder.Entity("ATag.Core.TaggedEntity", b =>
                {
                    b.HasOne("ATag.Core.Tag", "Tag")
                        .WithMany("TaggedEntities")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ATag.Core.TagNote", b =>
                {
                    b.HasOne("ATag.Core.TaggedEntity", "TaggedEntity")
                        .WithOne("TagNote")
                        .HasForeignKey("ATag.Core.TagNote", "Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("TaggedEntity");
                });

            modelBuilder.Entity("ATag.Core.Tag", b =>
                {
                    b.Navigation("TaggedEntities");
                });

            modelBuilder.Entity("ATag.Core.TaggedEntity", b =>
                {
                    b.Navigation("TagNote");
                });
#pragma warning restore 612, 618
        }
    }
}
